var kn = "Pisti";
var a = 2;
console.log(kn);
var vn = "Kis";
console.log(vn);
var kor = 32;
console.log(kor);
var nagykoru = false;
console.log(nagykoru);
var h = 220;
console.log(h);
var felnőtt;
console.log(vn + " felnőtt? "+ felnőtt);