
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Phone_name = @"K20 plus",
    Brand = @"LG",
    Os = @"Android 7.0",
    Resolution = @"720x1280",
    Battery = 2700F,
    Battery_type = @"Li-Ion",
    Ram_GB_ = 2F,
    Announcement_date = @"2016-12-01",
    Storage_GB_ = 16F,
    Video_720p = false,
    Video_1080p = true,
    Video_8K = @"False",
    Video_30fps = @"True",
    Video_60fps = false,
    Video_120fps = false,
    Video_240fps = false,
    Video_480fps = @"False",
    Video_960fps = false,
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Video_4K with predicted Video_4K from sample data...\n\n");


Console.WriteLine($"Phone_name: {@"K20 plus"}");
Console.WriteLine($"Brand: {@"LG"}");
Console.WriteLine($"Os: {@"Android 7.0"}");
Console.WriteLine($"Resolution: {@"720x1280"}");
Console.WriteLine($"Battery: {2700F}");
Console.WriteLine($"Battery_type: {@"Li-Ion"}");
Console.WriteLine($"Ram_GB_: {2F}");
Console.WriteLine($"Announcement_date: {@"2016-12-01"}");
Console.WriteLine($"Storage_GB_: {16F}");
Console.WriteLine($"Video_720p: {false}");
Console.WriteLine($"Video_1080p: {true}");
Console.WriteLine($"Video_4K: {false}");
Console.WriteLine($"Video_8K: {@"False"}");
Console.WriteLine($"Video_30fps: {@"True"}");
Console.WriteLine($"Video_60fps: {false}");
Console.WriteLine($"Video_120fps: {false}");
Console.WriteLine($"Video_240fps: {false}");
Console.WriteLine($"Video_480fps: {@"False"}");
Console.WriteLine($"Video_960fps: {false}");


Console.WriteLine($"\n\nPredicted Video_4K: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

